# Generated by Django 5.2.4 on 2025-08-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # Basic fields
                ("username", models.CharField(max_length=50, unique=True)),
                (
                    "password",
                    models.CharField(max_length=200),
                ),  # you changed this to support hashing later
                # New fields
                ("full_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(unique=True)),
                # role field (unchanged)
                ("role", models.CharField(default="user", max_length=20)),
            ],
        ),
    ]
